language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t shireenm/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shireenm/react-test npm test


after_success:
    - docker build -t shireenm/multi-client ./client
    - docker build -t shireenm/multi-nginx ./nginx
    - docker build -t shireenm/multi-server ./server
    - docker build -t shireenm/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  

    - docker push shireenm/multi-client
    - docker push shireenm/multi-nginx 
    - docker push shireenm/multi-server
    - docker push shireenm/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-598360529671'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY